name: Build, Test, Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install
        run: |
          npm install
          npm run build

      - name: Build
        run: |
          npm run build --if-present

      - name: Test 
        run: |
          npm run test
      
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.WORKFLOW_DEPLOYMENT_TOKEN }}
          repository: ${{ github.repository }}